### ISSUE TITLE
Gerbers or link to PCB

### ISSUE THREAD

**Issue by kylestew** [mxmxmx/minitrash#2]
How can I acquire or fab my own PCB for this? Seems like a good thing to get working with the new Teensy 4.

**Comment by mxmxmx** [comment]
hi kyle,

the thing is > 4 years old, i've deleted the gerbers at some point. you can still find them [here](https://github.com/mxmxmx/minitrash/tree/fb32a1a5392b86d12e0daf26ac52dc3fd1d5011a/hard). that said ... not sure i'd recommend building it now, at least i'd go about it a little differently. also re T4, the i2s pin out is different from T3.x, so you couldn't use it!

**Comment by kylestew** [comment]
Ha! Good to know the T4 isn't pin compatible. I shouldn't have assumed it was.

Thanks for the link! I will probably try and adapt the design for a new module. I'm hoping to make something like O_C but audio focused. It should be able to do things like a macro oscillator or digital filter. Seems like I need a codec with AC coupled ins/outs. The Eurotrash and minitrash seem like your closest modules. Can you recommend any existing modules that use the Teensy well for this. I have a Euroshield 1, but it needs more CV inputs and the STGL5000 isn't the best codec.

**Comment by mxmxmx** [comment]
There's probably not much right now (the i2s pins moved, so that should make pretty much any audio/codec module designed around 3.x incompatible (unless you'd use flying wires)). the SPI signals are still the same, so that might be an option (i've put this together during T4 beta testing, for [example](https://github.com/mxmxmx/telefuncen), but for audio, a codec might be preferable). (considering the T4's ADCs aren't the best quality/somewhat low res, an external ADC at any rate might be needed)

fwiw, i personally like PCM5102a, it's decent + very straightforward to use, but it has no inputs, of course (though there's matching ADCs, e.g. PCM1865); and there's a bunch of others that's already [supported](https://github.com/PaulStoffregen/Audio/blob/master/Audio.h#L68-L73). CS4272 is rather nice (i've used it [here](https://github.com/mxmxmx/usb_audio)), for instance.

**Comment by kylestew** [comment]
Awesome! Really appreciate your info here and on the teensy forums. I'm learning a lot from the designs and conversation.
